version: '3.9'

services:
  build:
    container_name: simple_docker_runner_build
    build:
      target: build
      context: .

  docker:
    container_name: simple_docker_runner
    build:
      target: docker
      context: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DOCKER_API_VERSION: 1.42
      ALLOWED_DOCKER_IMAGES: ${ALLOWED_DOCKER_IMAGES}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/docker
